apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruwd-ha-containers-deployment
  labels:
    app: ha-containers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ha-containers
  template:
    metadata:
      labels:
        app: ha-containers
    spec:
      containers:
      - name: ha-containers
        image: first-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
